<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018424"><DocLocation><![CDATA[C:\Users\SHOBIB\Documents\Unified Functional Testing\orange_hrm_dp]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[orange_hrm_dp]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:14]]></Time>
<TimeTick>1676024054</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:14]]></Time>
<TimeTick>1676024054</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:14]]></Time>
<TimeTick>1676024054</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e60e2dad2b2d7ffab62485d52c030ef25e606d2b48"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:14]]></Time>
<TimeTick>1676024054</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:14]]></Time>
<TimeTick>1676024054</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="2" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 15:44:14" eTime="10-02-2023 - 15:44:14" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[search]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:16]]></Time>
<TimeTick>1676024056</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:16]]></Time>
<TimeTick>1676024056</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Pim"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:16]]></Time>
<TimeTick>1676024056</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="27" Source="search" SourceLine="0" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:16]]></Time>
<TimeTick>1676024056</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="search" SourceLine="1" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="26" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:18]]></Time>
<TimeTick>1676024058</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:18]]></Time>
<TimeTick>1676024058</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="35" Source="search" SourceLine="2" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Admin.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:18]]></Time>
<TimeTick>1676024058</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" Source="search" SourceLine="3" >
<Disp><![CDATA[Admin.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="34" Source="search" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:19]]></Time>
<TimeTick>1676024059</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["pim"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:19]]></Time>
<TimeTick>1676024059</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="43" Source="search" SourceLine="4" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:20]]></Time>
<TimeTick>1676024060</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="search" SourceLine="5" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="42" Source="search" SourceLine="4" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 15:44:14" eTime="10-02-2023 - 15:44:20" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="21" >
<Disp><![CDATA[search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T21">
<AName><![CDATA[logout]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA["Suman chavan"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="91" status="Warning" Source="logout" SourceLine="0" >
<Disp><![CDATA["Suman chavan"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA["Suman chavan"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=Suman chavan<br>html tag=SPAN<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (73 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=SPAN<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 73 matches)</SPAN><br>class=oxd-userdropdown-tab<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=Suman chavan<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="92" Source="logout" SourceLine="0" >
<Disp><![CDATA["Suman chavan"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Suman chavan.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="93" Source="logout" SourceLine="0" >
<Disp><![CDATA[Suman chavan.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[About Support Change Password.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Logout"]]></Details>
<Time><![CDATA[10-02-2023 - 15:44:40]]></Time>
<TimeTick>1676024080</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="96" Source="logout" SourceLine="1" >
<Disp><![CDATA[About Support Change Password.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="90" status="Warning" Source="logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="89" status="Warning" Source="logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 15:44:20" eTime="10-02-2023 - 15:44:40" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="48" status="Warning" >
<Disp><![CDATA[logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[orange_hrm_dp Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10-02-2023 - 15:44:08" eTime="10-02-2023 - 15:44:40" passed="0" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test orange_hrm_dp Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>