<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018424"><DocLocation><![CDATA[C:\Users\SHOBIB\Documents\Unified Functional Testing\synchronization_demo]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[synchronization_demo]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample]]></Obj>
<Details plainTxt="False" ><![CDATA[WpfWindow]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:29]]></Time>
<TimeTick>1676270669</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[agentName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["john"]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:29]]></Time>
<TimeTick>1676270669</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Login" SourceLine="0" >
<Disp><![CDATA[agentName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["63e9d8d8791bc842c069"]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:29]]></Time>
<TimeTick>1676270669</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Login" SourceLine="1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OK.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:29]]></Time>
<TimeTick>1676270669</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Login" SourceLine="2" >
<Disp><![CDATA[OK.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:29]]></Time>
<TimeTick>1676270669</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="3" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:30]]></Time>
<TimeTick>1676270670</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="Login" SourceLine="4" >
<Disp><![CDATA[FIND FLIGHTS.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[FIND FLIGHTS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:30]]></Time>
<TimeTick>1676270670</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="22" Source="Login" SourceLine="5" >
<Disp><![CDATA[FIND FLIGHTS.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:30]]></Time>
<TimeTick>1676270670</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" Source="Login" SourceLine="6" >
<Disp><![CDATA[flightsDataGrid.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[flightsDataGrid.SelectCell]]></Obj>
<Details plainTxt="False" ><![CDATA[3, 2]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:30]]></Time>
<TimeTick>1676270670</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" Source="Login" SourceLine="7" >
<Disp><![CDATA[flightsDataGrid.SelectCell]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:31]]></Time>
<TimeTick>1676270671</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="Login" SourceLine="8" >
<Disp><![CDATA[SELECT FLIGHT.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SELECT FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:31]]></Time>
<TimeTick>1676270671</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="Login" SourceLine="9" >
<Disp><![CDATA[SELECT FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[passengerName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["shobitha"]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:31]]></Time>
<TimeTick>1676270671</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" Source="Login" SourceLine="10" >
<Disp><![CDATA[passengerName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[ORDER.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", False, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:41]]></Time>
<TimeTick>1676270681</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" status="Warning" Source="Login" SourceLine="11" >
<Disp><![CDATA[ORDER.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[ORDER.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:41]]></Time>
<TimeTick>1676270681</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" Source="Login" SourceLine="12" >
<Disp><![CDATA[ORDER.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Order 139 completed.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", "Order 139 completed", 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:52]]></Time>
<TimeTick>1676270692</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="38" status="Warning" Source="Login" SourceLine="13" >
<Disp><![CDATA[Order 139 completed.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[NEW SEARCH.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:52]]></Time>
<TimeTick>1676270692</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Login" SourceLine="14" >
<Disp><![CDATA[NEW SEARCH.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[fromCity.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 10000]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:52]]></Time>
<TimeTick>1676270692</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="Login" SourceLine="15" >
<Disp><![CDATA[fromCity.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Micro Focus MyFlight Sample.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-02-2023 - 12:14:52]]></Time>
<TimeTick>1676270692</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="44" Source="Login" SourceLine="16" >
<Disp><![CDATA[Micro Focus MyFlight Sample.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Warning" Source="Login" SourceLine="0" >
<Disp><![CDATA[Micro Focus MyFlight Sample]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-02-2023 - 12:14:28" eTime="13-02-2023 - 12:14:52" passed="0" failed="0" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[synchronization_demo Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-02-2023 - 12:14:27" eTime="13-02-2023 - 12:14:52" passed="0" failed="0" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test synchronization_demo Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>