<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018424"><DocLocation><![CDATA[C:\Users\SHOBIB\Documents\Unified Functional Testing\orange_hrm]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[orange_hrm]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:50:55]]></Time>
<TimeTick>1676006455</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:50:55]]></Time>
<TimeTick>1676006455</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[10-02-2023 - 10:50:55]]></Time>
<TimeTick>1676006455</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63e5d31a041dc1ee3374dd3bc09e99e7ecf90a9e5471"]]></Details>
<Time><![CDATA[10-02-2023 - 10:50:55]]></Time>
<TimeTick>1676006455</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Login" SourceLine="1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:50:55]]></Time>
<TimeTick>1676006455</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="2" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:50:35" eTime="10-02-2023 - 10:50:55" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[search]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:15]]></Time>
<TimeTick>1676006475</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:15]]></Time>
<TimeTick>1676006475</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0345"]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:15]]></Time>
<TimeTick>1676006475</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="search" SourceLine="0" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="25" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="24" Source="search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:50:55" eTime="10-02-2023 - 10:51:15" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="9" nRep="21" >
<Disp><![CDATA[search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[add_employee]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:35]]></Time>
<TimeTick>1676006495</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:35]]></Time>
<TimeTick>1676006495</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:35]]></Time>
<TimeTick>1676006495</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="add_employee" SourceLine="0" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:35]]></Time>
<TimeTick>1676006495</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="add_employee" SourceLine="1" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:36]]></Time>
<TimeTick>1676006496</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="39" Source="add_employee" SourceLine="2" >
<Disp><![CDATA[Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:36]]></Time>
<TimeTick>1676006496</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="add_employee" SourceLine="3" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="add_employee" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:37]]></Time>
<TimeTick>1676006497</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Add Employee.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:37]]></Time>
<TimeTick>1676006497</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="add_employee" SourceLine="4" >
<Disp><![CDATA[Add Employee.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" Source="add_employee" SourceLine="4" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["shobitha"]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="add_employee" SourceLine="5" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["gowda"]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="55" Source="add_employee" SourceLine="6" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="add_employee" SourceLine="7" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="51" Source="add_employee" SourceLine="5" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Employee List.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:39]]></Time>
<TimeTick>1676006499</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="62" Source="add_employee" SourceLine="8" >
<Disp><![CDATA[Employee List.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="61" Source="add_employee" SourceLine="8" >
<Disp><![CDATA[OrangeHRM_4]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:40]]></Time>
<TimeTick>1676006500</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Add Employee.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:51:40]]></Time>
<TimeTick>1676006500</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="67" Source="add_employee" SourceLine="9" >
<Disp><![CDATA[Add Employee.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="66" Source="add_employee" SourceLine="9" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="31" Source="add_employee" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:51:15" eTime="10-02-2023 - 10:51:40" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="28" >
<Disp><![CDATA[add_employee Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[employee_list]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:00]]></Time>
<TimeTick>1676006520</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:00]]></Time>
<TimeTick>1676006520</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Employee List.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:00]]></Time>
<TimeTick>1676006520</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="74" Source="employee_list" SourceLine="0" >
<Disp><![CDATA[Employee List.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="73" Source="employee_list" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:01]]></Time>
<TimeTick>1676006521</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["0351"]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:01]]></Time>
<TimeTick>1676006521</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="79" Source="employee_list" SourceLine="1" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:01]]></Time>
<TimeTick>1676006521</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" Source="employee_list" SourceLine="2" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[0351.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:02]]></Time>
<TimeTick>1676006522</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="86" Source="employee_list" SourceLine="3" >
<Disp><![CDATA[0351.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="78" Source="employee_list" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:03]]></Time>
<TimeTick>1676006523</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:03]]></Time>
<TimeTick>1676006523</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="91" Source="employee_list" SourceLine="4" >
<Disp><![CDATA[WebElement.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[-- Select --SingleMarriedOther.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Single"]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:04]]></Time>
<TimeTick>1676006524</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="94" Source="employee_list" SourceLine="5" >
<Disp><![CDATA[-- Select --SingleMarriedOther.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA["WebElement_2"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (11 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=WebElement<br>innertext=<br>html tag=I<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (13 objects found)&nbsp;</FONT></u><br>
micclass=WebElement<br>html tag=I<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
html id=<SPAN class=passed> (Used</SPAN>, 13 matches)</SPAN><br>class=oxd-icon bi-caret-up-fill oxd-select-text--arrow<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>innertext=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>acc_name=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:04]]></Time>
<TimeTick>1676006524</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="97" Source="employee_list" SourceLine="6" >
<Disp><![CDATA["WebElement_2"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[WebElement_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:04]]></Time>
<TimeTick>1676006524</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="98" Source="employee_list" SourceLine="6" >
<Disp><![CDATA[WebElement_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[-- Select --SingleMarriedOther]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"--&nbsp;Select&nbsp;--SingleMarriedOther"&nbsp;(of&nbsp;class&nbsp;WebList).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:25]]></Time>
<TimeTick>1676006545</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[-- Select --SingleMarriedOther]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = DIV<br>_xpath = //DIV[2]/DIV[1]/DIV[2]/DIV[1]/DIV[@role="listbox"][1]<br>|Visible Items = 4<br>Visible = -1<br>Name = select<br>Items Count = 4<br>Html Id = <br>first item = -- Select --<br>default value = <br>DHTML Class = oxd-select-dropdown --positon-bottom<br>acc_name = <br>]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:25]]></Time>
<TimeTick>1676006545</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="144" status="Warning" nType="Description" Source="employee_list" SourceLine="7" >
<Disp><![CDATA[-- Select --SingleMarriedOther]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="12" nRep="143" status="Failed" nType="Run Error" Source="employee_list" SourceLine="7" >
<Disp><![CDATA[-- Select --SingleMarriedOther]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="90" status="Failed" Source="employee_list" SourceLine="4" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="72" status="Failed" Source="employee_list" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:25]]></Time>
<TimeTick>1676006545</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;-- Select --SingleMarriedOther&quot; (of class WebList).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (8): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM_3&quot;).WebList(&quot;-- Select --SingleMarriedOther&quot;).Select &quot;Indian&quot;&quot;. ]]></Details>
<Time><![CDATA[10-02-2023 - 10:52:25]]></Time>
<TimeTick>1676006545</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="146" status="Failed" Source="employee_list" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[394996]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[10-02-2023 - 10:53:04]]></Time>
<TimeTick>1676006584</TimeTick>
<NodeArgs eType="General" icon="15" nRep="147" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="145" status="Failed" Source="employee_list" SourceLine="7" >
<Disp><![CDATA[OrangeHRM]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act4\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[394996]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="10-02-2023 - 10:51:40" eTime="10-02-2023 - 10:53:04" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="69" status="Failed" >
<Disp><![CDATA[employee_list Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[orange_hrm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="10-02-2023 - 10:50:27" eTime="10-02-2023 - 10:53:04" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test orange_hrm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>