<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="14.50" os="" host="LIN59018424"><DocLocation><![CDATA[C:\Users\SHOBIB\Documents\Unified Functional Testing\GUITest5_orange]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[GUITest5_orange]]></DName>
<Res><![CDATA[Res2]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:31]]></Time>
<TimeTick>1676386231</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:31]]></Time>
<TimeTick>1676386231</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:33]]></Time>
<TimeTick>1676386233</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[login]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:53]]></Time>
<TimeTick>1676386253</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:53]]></Time>
<TimeTick>1676386253</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA["username"- Description mismatch]]></Obj>
<Details plainTxt="False" ><![CDATA[The object was not found using the test object description. Check the object's properties.]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:53]]></Time>
<TimeTick>1676386253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="57" status="Warning" Source="login" SourceLine="0" >
<Disp><![CDATA["username"- Description mismatch]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA["username"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not found.</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=text<br>name=username<br>micclass=WebEdit<br>html tag=INPUT<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (1 objects found)&nbsp;</FONT></u><br>
type=text<br>micclass=WebEdit<br>html tag=INPUT<br>]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:53]]></Time>
<TimeTick>1676386253</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="58" Source="login" SourceLine="0" >
<Disp><![CDATA["username"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 20:20:53]]></Time>
<TimeTick>1676386253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="59" Source="login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"password"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 20:21:14]]></Time>
<TimeTick>1676386274</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = password<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //DIV/DIV/DIV/DIV/FORM/DIV/DIV[normalize-space()="Password"]/DIV[2]/INPUT[1]<br>|rows = 0<br>placeholder = Password<br>Name = password<br>Max Length = 524288<br>Html Id = <br>default value = <br>DHTML Class = oxd-input oxd-input--focus<br>acc_name = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 20:21:14]]></Time>
<TimeTick>1676386274</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="104" status="Warning" nType="Description" Source="login" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="103" status="Failed" nType="Run Error" Source="login" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" status="Failed" Source="login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="55" status="Failed" Source="login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 20:21:14]]></Time>
<TimeTick>1676386274</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;password&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM&quot;).WebEdit(&quot;password&quot;).SetSecure &quot;63eb9ee879e6cd3024e5df90bd02eb7ad8d228e2f7ec&quot;&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 20:21:14]]></Time>
<TimeTick>1676386274</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="106" status="Failed" Source="login" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[329516]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[14-02-2023 - 20:21:18]]></Time>
<TimeTick>1676386278</TimeTick>
<NodeArgs eType="General" icon="10" nRep="107" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="105" status="Failed" Source="login" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[329516]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 20:20:33" eTime="14-02-2023 - 20:21:18" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" status="Failed" >
<Disp><![CDATA[login Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[GUITest5_orange Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 20:20:30" eTime="14-02-2023 - 20:21:18" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test GUITest5_orange Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>